### ISSUE TITLE
无此必要

### ISSUE THREAD

**Issue by EillesWan** [eggylan/MCStruct2FuncPy#1]
非常抱歉，这样说恐怕有点不礼貌……但是。。。
我已经写过了，况且这个功能在现在没什么特别大的需求。
如果有想法，可以来和我一起开发点新东西，欸嘿~

**Comment by eggylan** [comment]
**非常感谢你的issue！**

> 非常抱歉，这样说恐怕有点不礼貌……

礼貌问题我并不计较，别人能把意思传达给我就行。

> 况且这个功能在现在没什么特别大的需求。

实际上，结构转mc函数这个功能在网易mcPC端联机大厅的需求是*相当大*的。考虑到网易租赁服的成本问题，不少玩家在联机大厅开“伪服务器”，即腐竹开一个房主号挂在房间以维持房间的存在，其他玩家进入房间游玩。
![screenshot2024124848](https://github.com/user-attachments/assets/81de67bb-f9f3-44cf-be99-3c4b06e6f224)
由于ModAPI里并没有给出直接上传本地mcstructure的接口，玩家们如果需要向游戏内导入建筑，必须使用“转换器”把结构文件转换为mc的指令（主要为`/setblock`,` /fill`），然后使用“导入器”（包括发包，或者模拟键盘输入）输入这些指令放置方块。

> 我已经写过了…………如果有想法，可以来和我一起开发点新东西

非常感谢你的认可，不过很遗憾本人才疏学浅，在很多方面完全是个菜鸡，对编程还停留在边做边学的状态，本想打算用这个项目练练手。如果以后有机会的话，我会很乐意加入 :)
